spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checkout
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
#  cloud:
#    stream:
#      kafka:
#        binder:
#          autoCreateTopics: false
#          brokers: localhost:9892
#          configuration:
#            value:
#              deserializer: io.confluent.kafka.serializers.kafkaAvroDeserializer
#              serializer: io.confluent.kafka.serializers.kafkaAvroSerializer
#            key:
#              deserializer: io.confluent.kafka.serializers.kafkaAvroDeserializer
#              serializer: io.confluent.kafka.serializers.kafkaAvroSerializer





